export const transactions = [
    {
      orderId: '1',
      orderAmount: 100.00,
      date: '2022-01-01',
      customer:"Sample",
      status: 'Processing',
    },
    {
      orderId: '2',
      orderAmount: 200.00,
      date: '2022-01-05',
      customer:"Sample",
      status: 'completed',
    },
    {
      orderId: '3',
      orderAmount: 50.00,
      date: '2022-01-10',
      customer:"Sample",
      status: 'cancelled',
    },
    {
        orderId: '4',
        orderAmount: 50.00,
        date: '2022-01-10',
        customer:"Sample",
        status: 'cancelled',
      },
      {
        orderId: '5',
        orderAmount: 50.00,
        date: '2022-01-10',
        customer:"Sample",
        status: 'cancelled',
      },
      {
        orderId: '6',
        orderAmount: 100.00,
        date: '2022-01-01',
        customer:"Sample",
        status: 'Processing',
      },
      {
        orderId: '7',
        orderAmount: 200.00,
        date: '2022-01-05',
        customer:"Sample",
        status: 'completed',
      },
      {
        orderId: '8',
        orderAmount: 50.00,
        date: '2022-01-10',
        customer:"Sample",
        status: 'cancelled',
      },
      {
          orderId: '9',
          orderAmount: 50.00,
          date: '2022-01-10',
          customer:"Sample",
          status: 'cancelled',
        },
        {
          orderId: '10',
          orderAmount: 50.00,
          date: '2022-01-10',
          customer:"Sample",
          status: 'cancelled',
        },
    // add more transactions data here
  ];